// Code generated by cgen. DO NOT EDIT.
package gdc

// #cgo CFLAGS: -I${SRCDIR}/../gdraw
/*
#include <string.h>

#include <stdlib.h>
#include "interface.gen.h"

*/
import "C"

import (

  "fmt"

	"unsafe"
)

type Interface interface {
  ArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) VariantPtr
  ArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) VariantPtr
  ArrayRef(pSelf TypePtr, pFrom ConstTypePtr, ) 
  ArraySetTyped(pSelf TypePtr, pType VariantType, pClassName ConstStringNamePtr, pScript ConstVariantPtr, ) 
  ClassdbConstructObject(pClassname ConstStringNamePtr, ) ObjectPtr
  ClassdbGetClassTag(pClassname ConstStringNamePtr, ) unsafe.Pointer
  ClassdbGetMethodBind(pClassname ConstStringNamePtr, pMethodname ConstStringNamePtr, pHash Int, ) MethodBindPtr
  ClassdbRegisterExtensionClass(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, pParentClassName ConstStringNamePtr, pExtensionFuncs *ClassCreationInfo, ) 
  ClassdbRegisterExtensionClassIntegerConstant(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, pEnumName ConstStringNamePtr, pConstantName ConstStringNamePtr, pConstantValue Int, pIsBitfield Bool, ) 
  ClassdbRegisterExtensionClassMethod(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, pMethodInfo *ClassMethodInfo, ) 
  ClassdbRegisterExtensionClassProperty(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, pInfo *PropertyInfo, pSetter ConstStringNamePtr, pGetter ConstStringNamePtr, ) 
  ClassdbRegisterExtensionClassPropertyGroup(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, pGroupName ConstStringPtr, pPrefix ConstStringPtr, ) 
  ClassdbRegisterExtensionClassPropertySubgroup(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, pSubgroupName ConstStringPtr, pPrefix ConstStringPtr, ) 
  ClassdbRegisterExtensionClassSignal(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, pSignalName ConstStringNamePtr, pArgumentInfo *PropertyInfo, pArgumentCount Int, ) 
  ClassdbUnregisterExtensionClass(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, ) 
  DictionaryOperatorIndex(pSelf TypePtr, pKey ConstVariantPtr, ) VariantPtr
  DictionaryOperatorIndexConst(pSelf ConstTypePtr, pKey ConstVariantPtr, ) VariantPtr
  EditorAddPlugin(pClassName ConstStringNamePtr, ) 
  EditorRemovePlugin(pClassName ConstStringNamePtr, ) 
  FileAccessGetBuffer(pInstance ConstObjectPtr, pDst *uint8, pLength uint64, ) uint64
  FileAccessStoreBuffer(pInstance ObjectPtr, pSrc *uint8, pLength uint64, ) 
  GetGodotVersion(rGodotVersion *GodotVersion, ) 
  GetLibraryPath(pLibrary ClassLibraryPtr, rPath UninitializedStringPtr, ) 
  GetNativeStructSize(pName ConstStringNamePtr, ) uint64
  GetVariantFromTypeConstructor(pType VariantType, ) VariantFromTypeConstructorFunc
  GetVariantToTypeConstructor(pType VariantType, ) TypeFromVariantConstructorFunc
  GlobalGetSingleton(pName ConstStringNamePtr, ) ObjectPtr
  MemAlloc(pBytes uint64, ) unsafe.Pointer
  MemFree(pPtr unsafe.Pointer, ) 
  MemRealloc(pPtr unsafe.Pointer, pBytes uint64, ) unsafe.Pointer
  ObjectCastTo(pObject ConstObjectPtr, pClassTag unsafe.Pointer, ) ObjectPtr
  ObjectDestroy(pO ObjectPtr, ) 
  ObjectGetClassName(pObject ConstObjectPtr, pLibrary ClassLibraryPtr, rClassName UninitializedStringNamePtr, ) Bool
  ObjectGetInstanceBinding(pO ObjectPtr, pToken unsafe.Pointer, pCallbacks *InstanceBindingCallbacks, ) unsafe.Pointer
  ObjectGetInstanceFromId(pInstanceId uint64, ) ObjectPtr
  ObjectGetInstanceId(pObject ConstObjectPtr, ) uint64
  ObjectMethodBindCall(pMethodBind MethodBindPtr, pInstance ObjectPtr, pArgs *ConstVariantPtr, pArgCount Int, rRet UninitializedVariantPtr, rError *CallError, ) 
  ObjectMethodBindPtrcall(pMethodBind MethodBindPtr, pInstance ObjectPtr, pArgs *ConstTypePtr, rRet TypePtr, ) 
  ObjectSetInstance(pO ObjectPtr, pClassname ConstStringNamePtr, pInstance ClassInstancePtr, ) 
  ObjectSetInstanceBinding(pO ObjectPtr, pToken unsafe.Pointer, pBinding unsafe.Pointer, pCallbacks *InstanceBindingCallbacks, ) 
  PackedByteArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) *uint8
  PackedByteArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) *uint8
  PackedColorArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) TypePtr
  PackedColorArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) TypePtr
  PackedFloat32ArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) *float32
  PackedFloat32ArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) *float32
  PackedFloat64ArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) *float64
  PackedFloat64ArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) *float64
  PackedInt32ArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) *int
  PackedInt32ArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) *int
  PackedInt64ArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) *int64
  PackedInt64ArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) *int64
  PackedStringArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) StringPtr
  PackedStringArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) StringPtr
  PackedVector2ArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) TypePtr
  PackedVector2ArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) TypePtr
  PackedVector3ArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) TypePtr
  PackedVector3ArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) TypePtr
  PrintError(pDescription string, pFunction string, pFile string, pLine int, pEditorNotify Bool, ) 
  PrintErrorWithMessage(pDescription string, pMessage string, pFunction string, pFile string, pLine int, pEditorNotify Bool, ) 
  PrintScriptError(pDescription string, pFunction string, pFile string, pLine int, pEditorNotify Bool, ) 
  PrintScriptErrorWithMessage(pDescription string, pMessage string, pFunction string, pFile string, pLine int, pEditorNotify Bool, ) 
  PrintWarning(pDescription string, pFunction string, pFile string, pLine int, pEditorNotify Bool, ) 
  PrintWarningWithMessage(pDescription string, pMessage string, pFunction string, pFile string, pLine int, pEditorNotify Bool, ) 
  RefGetObject(pRef ConstRefPtr, ) ObjectPtr
  RefSetObject(pRef RefPtr, pObject ObjectPtr, ) 
  ScriptInstanceCreate(pInfo *ScriptInstanceInfo, pInstanceData ScriptInstanceDataPtr, ) ScriptInstancePtr
  StringNewWithLatin1Chars(rDest UninitializedStringPtr, pContents string, ) 
  StringNewWithLatin1CharsAndLen(rDest UninitializedStringPtr, pContents string, pSize Int, ) 
  StringNewWithUtf16Chars(rDest UninitializedStringPtr, pContents *uint16, ) 
  StringNewWithUtf16CharsAndLen(rDest UninitializedStringPtr, pContents *uint16, pSize Int, ) 
  StringNewWithUtf32Chars(rDest UninitializedStringPtr, pContents *uint, ) 
  StringNewWithUtf32CharsAndLen(rDest UninitializedStringPtr, pContents *uint, pSize Int, ) 
  StringNewWithUtf8Chars(rDest UninitializedStringPtr, pContents string, ) 
  StringNewWithUtf8CharsAndLen(rDest UninitializedStringPtr, pContents string, pSize Int, ) 
  StringNewWithWideChars(rDest UninitializedStringPtr, pContents *int, ) 
  StringNewWithWideCharsAndLen(rDest UninitializedStringPtr, pContents *int, pSize Int, ) 
  StringOperatorIndex(pSelf StringPtr, pIndex Int, ) *uint
  StringOperatorIndexConst(pSelf ConstStringPtr, pIndex Int, ) *uint
  StringOperatorPlusEqC32Str(pSelf StringPtr, pB *uint, ) 
  StringOperatorPlusEqChar(pSelf StringPtr, pB uint, ) 
  StringOperatorPlusEqCstr(pSelf StringPtr, pB string, ) 
  StringOperatorPlusEqString(pSelf StringPtr, pB ConstStringPtr, ) 
  StringOperatorPlusEqWcstr(pSelf StringPtr, pB *int, ) 
  StringToLatin1Chars(pSelf ConstStringPtr, rText string, pMaxWriteLength Int, ) Int
  StringToUtf16Chars(pSelf ConstStringPtr, rText *uint16, pMaxWriteLength Int, ) Int
  StringToUtf32Chars(pSelf ConstStringPtr, rText *uint, pMaxWriteLength Int, ) Int
  StringToUtf8Chars(pSelf ConstStringPtr, rText string, pMaxWriteLength Int, ) Int
  StringToWideChars(pSelf ConstStringPtr, rText *int, pMaxWriteLength Int, ) Int
  VariantBooleanize(pSelf ConstVariantPtr, ) Bool
  VariantCall(pSelf VariantPtr, pMethod ConstStringNamePtr, pArgs *ConstVariantPtr, pArgumentCount Int, rReturn UninitializedVariantPtr, rError *CallError, ) 
  VariantCallStatic(pType VariantType, pMethod ConstStringNamePtr, pArgs *ConstVariantPtr, pArgumentCount Int, rReturn UninitializedVariantPtr, rError *CallError, ) 
  VariantCanConvert(pFrom VariantType, pTo VariantType, ) Bool
  VariantCanConvertStrict(pFrom VariantType, pTo VariantType, ) Bool
  VariantConstruct(pType VariantType, rBase UninitializedVariantPtr, pArgs *ConstVariantPtr, pArgumentCount int, rError *CallError, ) 
  VariantDestroy(pSelf VariantPtr, ) 
  VariantDuplicate(pSelf ConstVariantPtr, rRet VariantPtr, pDeep Bool, ) 
  VariantEvaluate(pOp VariantOperator, pA ConstVariantPtr, pB ConstVariantPtr, rReturn UninitializedVariantPtr, rValid *uint8, ) 
  VariantGet(pSelf ConstVariantPtr, pKey ConstVariantPtr, rRet UninitializedVariantPtr, rValid *uint8, ) 
  VariantGetConstantValue(pType VariantType, pConstant ConstStringNamePtr, rRet UninitializedVariantPtr, ) 
  VariantGetIndexed(pSelf ConstVariantPtr, pIndex Int, rRet UninitializedVariantPtr, rValid *uint8, rOob *uint8, ) 
  VariantGetKeyed(pSelf ConstVariantPtr, pKey ConstVariantPtr, rRet UninitializedVariantPtr, rValid *uint8, ) 
  VariantGetNamed(pSelf ConstVariantPtr, pKey ConstStringNamePtr, rRet UninitializedVariantPtr, rValid *uint8, ) 
  VariantGetPtrBuiltinMethod(pType VariantType, pMethod ConstStringNamePtr, pHash Int, ) PtrBuiltInMethod
  VariantGetPtrConstructor(pType VariantType, pConstructor int, ) PtrConstructor
  VariantGetPtrDestructor(pType VariantType, ) PtrDestructor
  VariantGetPtrGetter(pType VariantType, pMember ConstStringNamePtr, ) PtrGetter
  VariantGetPtrIndexedGetter(pType VariantType, ) PtrIndexedGetter
  VariantGetPtrIndexedSetter(pType VariantType, ) PtrIndexedSetter
  VariantGetPtrKeyedChecker(pType VariantType, ) PtrKeyedChecker
  VariantGetPtrKeyedGetter(pType VariantType, ) PtrKeyedGetter
  VariantGetPtrKeyedSetter(pType VariantType, ) PtrKeyedSetter
  VariantGetPtrOperatorEvaluator(pOperator VariantOperator, pTypeA VariantType, pTypeB VariantType, ) PtrOperatorEvaluator
  VariantGetPtrSetter(pType VariantType, pMember ConstStringNamePtr, ) PtrSetter
  VariantGetPtrUtilityFunction(pFunction ConstStringNamePtr, pHash Int, ) PtrUtilityFunction
  VariantGetType(pSelf ConstVariantPtr, ) VariantType
  VariantGetTypeName(pType VariantType, rName UninitializedStringPtr, ) 
  VariantHasKey(pSelf ConstVariantPtr, pKey ConstVariantPtr, rValid *uint8, ) Bool
  VariantHasMember(pType VariantType, pMember ConstStringNamePtr, ) Bool
  VariantHasMethod(pSelf ConstVariantPtr, pMethod ConstStringNamePtr, ) Bool
  VariantHash(pSelf ConstVariantPtr, ) Int
  VariantHashCompare(pSelf ConstVariantPtr, pOther ConstVariantPtr, ) Bool
  VariantIterGet(pSelf ConstVariantPtr, rIter VariantPtr, rRet UninitializedVariantPtr, rValid *uint8, ) 
  VariantIterInit(pSelf ConstVariantPtr, rIter UninitializedVariantPtr, rValid *uint8, ) Bool
  VariantIterNext(pSelf ConstVariantPtr, rIter VariantPtr, rValid *uint8, ) Bool
  VariantNewCopy(rDest UninitializedVariantPtr, pSrc ConstVariantPtr, ) 
  VariantNewNil(rDest UninitializedVariantPtr, ) 
  VariantRecursiveHash(pSelf ConstVariantPtr, pRecursionCount Int, ) Int
  VariantSet(pSelf VariantPtr, pKey ConstVariantPtr, pValue ConstVariantPtr, rValid *uint8, ) 
  VariantSetIndexed(pSelf VariantPtr, pIndex Int, pValue ConstVariantPtr, rValid *uint8, rOob *uint8, ) 
  VariantSetKeyed(pSelf VariantPtr, pKey ConstVariantPtr, pValue ConstVariantPtr, rValid *uint8, ) 
  VariantSetNamed(pSelf VariantPtr, pKey ConstStringNamePtr, pValue ConstVariantPtr, rValid *uint8, ) 
  VariantStringify(pSelf ConstVariantPtr, rRet StringPtr, ) 
  WorkerThreadPoolAddNativeGroupTask(pInstance ObjectPtr, pFunc unsafe.Pointer, pUserdata unsafe.Pointer, pElements int, pTasks int, pHighPriority Bool, pDescription ConstStringPtr, ) int64
  WorkerThreadPoolAddNativeTask(pInstance ObjectPtr, pFunc unsafe.Pointer, pUserdata unsafe.Pointer, pHighPriority Bool, pDescription ConstStringPtr, ) int64
  XmlParserOpenBuffer(pInstance ObjectPtr, pBuffer *uint8, pSize uint64, ) Int
}

func callGetProcAddress[T any](getProcAddr InterfaceGetProcAddress, proc string) (T, error) {
  cProc := C.CString(proc)
  defer C.free(unsafe.Pointer(cProc))

  ptr := C.callGetProcAddress(getProcAddr, cProc)
  finalPtr := *(*T)(unsafe.Pointer(&ptr))
  if ptr == nil {
    return finalPtr, fmt.Errorf("failed to get proc address for %q", proc)
  }
  return finalPtr, nil
}

// NewInterface returns a wrapper allowing you to call methods from GDExtension
func NewInterface(getProcAddr InterfaceGetProcAddress) (Interface, error) {
  iface := &interfaceImpl{
  }
  var err error

  iface.ptrArrayOperatorIndex, err = callGetProcAddress[InterfaceArrayOperatorIndex](getProcAddr, "array_operator_index")
  if err != nil {
    return nil, err
  }

  iface.ptrArrayOperatorIndexConst, err = callGetProcAddress[InterfaceArrayOperatorIndexConst](getProcAddr, "array_operator_index_const")
  if err != nil {
    return nil, err
  }

  iface.ptrArrayRef, err = callGetProcAddress[InterfaceArrayRef](getProcAddr, "array_ref")
  if err != nil {
    return nil, err
  }

  iface.ptrArraySetTyped, err = callGetProcAddress[InterfaceArraySetTyped](getProcAddr, "array_set_typed")
  if err != nil {
    return nil, err
  }

  iface.ptrClassdbConstructObject, err = callGetProcAddress[InterfaceClassdbConstructObject](getProcAddr, "classdb_construct_object")
  if err != nil {
    return nil, err
  }

  iface.ptrClassdbGetClassTag, err = callGetProcAddress[InterfaceClassdbGetClassTag](getProcAddr, "classdb_get_class_tag")
  if err != nil {
    return nil, err
  }

  iface.ptrClassdbGetMethodBind, err = callGetProcAddress[InterfaceClassdbGetMethodBind](getProcAddr, "classdb_get_method_bind")
  if err != nil {
    return nil, err
  }

  iface.ptrClassdbRegisterExtensionClass, err = callGetProcAddress[InterfaceClassdbRegisterExtensionClass](getProcAddr, "classdb_register_extension_class")
  if err != nil {
    return nil, err
  }

  iface.ptrClassdbRegisterExtensionClassIntegerConstant, err = callGetProcAddress[InterfaceClassdbRegisterExtensionClassIntegerConstant](getProcAddr, "classdb_register_extension_class_integer_constant")
  if err != nil {
    return nil, err
  }

  iface.ptrClassdbRegisterExtensionClassMethod, err = callGetProcAddress[InterfaceClassdbRegisterExtensionClassMethod](getProcAddr, "classdb_register_extension_class_method")
  if err != nil {
    return nil, err
  }

  iface.ptrClassdbRegisterExtensionClassProperty, err = callGetProcAddress[InterfaceClassdbRegisterExtensionClassProperty](getProcAddr, "classdb_register_extension_class_property")
  if err != nil {
    return nil, err
  }

  iface.ptrClassdbRegisterExtensionClassPropertyGroup, err = callGetProcAddress[InterfaceClassdbRegisterExtensionClassPropertyGroup](getProcAddr, "classdb_register_extension_class_property_group")
  if err != nil {
    return nil, err
  }

  iface.ptrClassdbRegisterExtensionClassPropertySubgroup, err = callGetProcAddress[InterfaceClassdbRegisterExtensionClassPropertySubgroup](getProcAddr, "classdb_register_extension_class_property_subgroup")
  if err != nil {
    return nil, err
  }

  iface.ptrClassdbRegisterExtensionClassSignal, err = callGetProcAddress[InterfaceClassdbRegisterExtensionClassSignal](getProcAddr, "classdb_register_extension_class_signal")
  if err != nil {
    return nil, err
  }

  iface.ptrClassdbUnregisterExtensionClass, err = callGetProcAddress[InterfaceClassdbUnregisterExtensionClass](getProcAddr, "classdb_unregister_extension_class")
  if err != nil {
    return nil, err
  }

  iface.ptrDictionaryOperatorIndex, err = callGetProcAddress[InterfaceDictionaryOperatorIndex](getProcAddr, "dictionary_operator_index")
  if err != nil {
    return nil, err
  }

  iface.ptrDictionaryOperatorIndexConst, err = callGetProcAddress[InterfaceDictionaryOperatorIndexConst](getProcAddr, "dictionary_operator_index_const")
  if err != nil {
    return nil, err
  }

  iface.ptrEditorAddPlugin, err = callGetProcAddress[InterfaceEditorAddPlugin](getProcAddr, "editor_add_plugin")
  if err != nil {
    return nil, err
  }

  iface.ptrEditorRemovePlugin, err = callGetProcAddress[InterfaceEditorRemovePlugin](getProcAddr, "editor_remove_plugin")
  if err != nil {
    return nil, err
  }

  iface.ptrFileAccessGetBuffer, err = callGetProcAddress[InterfaceFileAccessGetBuffer](getProcAddr, "file_access_get_buffer")
  if err != nil {
    return nil, err
  }

  iface.ptrFileAccessStoreBuffer, err = callGetProcAddress[InterfaceFileAccessStoreBuffer](getProcAddr, "file_access_store_buffer")
  if err != nil {
    return nil, err
  }

  iface.ptrGetGodotVersion, err = callGetProcAddress[InterfaceGetGodotVersion](getProcAddr, "get_godot_version")
  if err != nil {
    return nil, err
  }

  iface.ptrGetLibraryPath, err = callGetProcAddress[InterfaceGetLibraryPath](getProcAddr, "get_library_path")
  if err != nil {
    return nil, err
  }

  iface.ptrGetNativeStructSize, err = callGetProcAddress[InterfaceGetNativeStructSize](getProcAddr, "get_native_struct_size")
  if err != nil {
    return nil, err
  }

  iface.ptrGetVariantFromTypeConstructor, err = callGetProcAddress[InterfaceGetVariantFromTypeConstructor](getProcAddr, "get_variant_from_type_constructor")
  if err != nil {
    return nil, err
  }

  iface.ptrGetVariantToTypeConstructor, err = callGetProcAddress[InterfaceGetVariantToTypeConstructor](getProcAddr, "get_variant_to_type_constructor")
  if err != nil {
    return nil, err
  }

  iface.ptrGlobalGetSingleton, err = callGetProcAddress[InterfaceGlobalGetSingleton](getProcAddr, "global_get_singleton")
  if err != nil {
    return nil, err
  }

  iface.ptrMemAlloc, err = callGetProcAddress[InterfaceMemAlloc](getProcAddr, "mem_alloc")
  if err != nil {
    return nil, err
  }

  iface.ptrMemFree, err = callGetProcAddress[InterfaceMemFree](getProcAddr, "mem_free")
  if err != nil {
    return nil, err
  }

  iface.ptrMemRealloc, err = callGetProcAddress[InterfaceMemRealloc](getProcAddr, "mem_realloc")
  if err != nil {
    return nil, err
  }

  iface.ptrObjectCastTo, err = callGetProcAddress[InterfaceObjectCastTo](getProcAddr, "object_cast_to")
  if err != nil {
    return nil, err
  }

  iface.ptrObjectDestroy, err = callGetProcAddress[InterfaceObjectDestroy](getProcAddr, "object_destroy")
  if err != nil {
    return nil, err
  }

  iface.ptrObjectGetClassName, err = callGetProcAddress[InterfaceObjectGetClassName](getProcAddr, "object_get_class_name")
  if err != nil {
    return nil, err
  }

  iface.ptrObjectGetInstanceBinding, err = callGetProcAddress[InterfaceObjectGetInstanceBinding](getProcAddr, "object_get_instance_binding")
  if err != nil {
    return nil, err
  }

  iface.ptrObjectGetInstanceFromId, err = callGetProcAddress[InterfaceObjectGetInstanceFromId](getProcAddr, "object_get_instance_from_id")
  if err != nil {
    return nil, err
  }

  iface.ptrObjectGetInstanceId, err = callGetProcAddress[InterfaceObjectGetInstanceId](getProcAddr, "object_get_instance_id")
  if err != nil {
    return nil, err
  }

  iface.ptrObjectMethodBindCall, err = callGetProcAddress[InterfaceObjectMethodBindCall](getProcAddr, "object_method_bind_call")
  if err != nil {
    return nil, err
  }

  iface.ptrObjectMethodBindPtrcall, err = callGetProcAddress[InterfaceObjectMethodBindPtrcall](getProcAddr, "object_method_bind_ptrcall")
  if err != nil {
    return nil, err
  }

  iface.ptrObjectSetInstance, err = callGetProcAddress[InterfaceObjectSetInstance](getProcAddr, "object_set_instance")
  if err != nil {
    return nil, err
  }

  iface.ptrObjectSetInstanceBinding, err = callGetProcAddress[InterfaceObjectSetInstanceBinding](getProcAddr, "object_set_instance_binding")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedByteArrayOperatorIndex, err = callGetProcAddress[InterfacePackedByteArrayOperatorIndex](getProcAddr, "packed_byte_array_operator_index")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedByteArrayOperatorIndexConst, err = callGetProcAddress[InterfacePackedByteArrayOperatorIndexConst](getProcAddr, "packed_byte_array_operator_index_const")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedColorArrayOperatorIndex, err = callGetProcAddress[InterfacePackedColorArrayOperatorIndex](getProcAddr, "packed_color_array_operator_index")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedColorArrayOperatorIndexConst, err = callGetProcAddress[InterfacePackedColorArrayOperatorIndexConst](getProcAddr, "packed_color_array_operator_index_const")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedFloat32ArrayOperatorIndex, err = callGetProcAddress[InterfacePackedFloat32ArrayOperatorIndex](getProcAddr, "packed_float32_array_operator_index")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedFloat32ArrayOperatorIndexConst, err = callGetProcAddress[InterfacePackedFloat32ArrayOperatorIndexConst](getProcAddr, "packed_float32_array_operator_index_const")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedFloat64ArrayOperatorIndex, err = callGetProcAddress[InterfacePackedFloat64ArrayOperatorIndex](getProcAddr, "packed_float64_array_operator_index")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedFloat64ArrayOperatorIndexConst, err = callGetProcAddress[InterfacePackedFloat64ArrayOperatorIndexConst](getProcAddr, "packed_float64_array_operator_index_const")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedInt32ArrayOperatorIndex, err = callGetProcAddress[InterfacePackedInt32ArrayOperatorIndex](getProcAddr, "packed_int32_array_operator_index")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedInt32ArrayOperatorIndexConst, err = callGetProcAddress[InterfacePackedInt32ArrayOperatorIndexConst](getProcAddr, "packed_int32_array_operator_index_const")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedInt64ArrayOperatorIndex, err = callGetProcAddress[InterfacePackedInt64ArrayOperatorIndex](getProcAddr, "packed_int64_array_operator_index")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedInt64ArrayOperatorIndexConst, err = callGetProcAddress[InterfacePackedInt64ArrayOperatorIndexConst](getProcAddr, "packed_int64_array_operator_index_const")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedStringArrayOperatorIndex, err = callGetProcAddress[InterfacePackedStringArrayOperatorIndex](getProcAddr, "packed_string_array_operator_index")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedStringArrayOperatorIndexConst, err = callGetProcAddress[InterfacePackedStringArrayOperatorIndexConst](getProcAddr, "packed_string_array_operator_index_const")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedVector2ArrayOperatorIndex, err = callGetProcAddress[InterfacePackedVector2ArrayOperatorIndex](getProcAddr, "packed_vector2_array_operator_index")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedVector2ArrayOperatorIndexConst, err = callGetProcAddress[InterfacePackedVector2ArrayOperatorIndexConst](getProcAddr, "packed_vector2_array_operator_index_const")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedVector3ArrayOperatorIndex, err = callGetProcAddress[InterfacePackedVector3ArrayOperatorIndex](getProcAddr, "packed_vector3_array_operator_index")
  if err != nil {
    return nil, err
  }

  iface.ptrPackedVector3ArrayOperatorIndexConst, err = callGetProcAddress[InterfacePackedVector3ArrayOperatorIndexConst](getProcAddr, "packed_vector3_array_operator_index_const")
  if err != nil {
    return nil, err
  }

  iface.ptrPrintError, err = callGetProcAddress[InterfacePrintError](getProcAddr, "print_error")
  if err != nil {
    return nil, err
  }

  iface.ptrPrintErrorWithMessage, err = callGetProcAddress[InterfacePrintErrorWithMessage](getProcAddr, "print_error_with_message")
  if err != nil {
    return nil, err
  }

  iface.ptrPrintScriptError, err = callGetProcAddress[InterfacePrintScriptError](getProcAddr, "print_script_error")
  if err != nil {
    return nil, err
  }

  iface.ptrPrintScriptErrorWithMessage, err = callGetProcAddress[InterfacePrintScriptErrorWithMessage](getProcAddr, "print_script_error_with_message")
  if err != nil {
    return nil, err
  }

  iface.ptrPrintWarning, err = callGetProcAddress[InterfacePrintWarning](getProcAddr, "print_warning")
  if err != nil {
    return nil, err
  }

  iface.ptrPrintWarningWithMessage, err = callGetProcAddress[InterfacePrintWarningWithMessage](getProcAddr, "print_warning_with_message")
  if err != nil {
    return nil, err
  }

  iface.ptrRefGetObject, err = callGetProcAddress[InterfaceRefGetObject](getProcAddr, "ref_get_object")
  if err != nil {
    return nil, err
  }

  iface.ptrRefSetObject, err = callGetProcAddress[InterfaceRefSetObject](getProcAddr, "ref_set_object")
  if err != nil {
    return nil, err
  }

  iface.ptrScriptInstanceCreate, err = callGetProcAddress[InterfaceScriptInstanceCreate](getProcAddr, "script_instance_create")
  if err != nil {
    return nil, err
  }

  iface.ptrStringNewWithLatin1Chars, err = callGetProcAddress[InterfaceStringNewWithLatin1Chars](getProcAddr, "string_new_with_latin1_chars")
  if err != nil {
    return nil, err
  }

  iface.ptrStringNewWithLatin1CharsAndLen, err = callGetProcAddress[InterfaceStringNewWithLatin1CharsAndLen](getProcAddr, "string_new_with_latin1_chars_and_len")
  if err != nil {
    return nil, err
  }

  iface.ptrStringNewWithUtf16Chars, err = callGetProcAddress[InterfaceStringNewWithUtf16Chars](getProcAddr, "string_new_with_utf16_chars")
  if err != nil {
    return nil, err
  }

  iface.ptrStringNewWithUtf16CharsAndLen, err = callGetProcAddress[InterfaceStringNewWithUtf16CharsAndLen](getProcAddr, "string_new_with_utf16_chars_and_len")
  if err != nil {
    return nil, err
  }

  iface.ptrStringNewWithUtf32Chars, err = callGetProcAddress[InterfaceStringNewWithUtf32Chars](getProcAddr, "string_new_with_utf32_chars")
  if err != nil {
    return nil, err
  }

  iface.ptrStringNewWithUtf32CharsAndLen, err = callGetProcAddress[InterfaceStringNewWithUtf32CharsAndLen](getProcAddr, "string_new_with_utf32_chars_and_len")
  if err != nil {
    return nil, err
  }

  iface.ptrStringNewWithUtf8Chars, err = callGetProcAddress[InterfaceStringNewWithUtf8Chars](getProcAddr, "string_new_with_utf8_chars")
  if err != nil {
    return nil, err
  }

  iface.ptrStringNewWithUtf8CharsAndLen, err = callGetProcAddress[InterfaceStringNewWithUtf8CharsAndLen](getProcAddr, "string_new_with_utf8_chars_and_len")
  if err != nil {
    return nil, err
  }

  iface.ptrStringNewWithWideChars, err = callGetProcAddress[InterfaceStringNewWithWideChars](getProcAddr, "string_new_with_wide_chars")
  if err != nil {
    return nil, err
  }

  iface.ptrStringNewWithWideCharsAndLen, err = callGetProcAddress[InterfaceStringNewWithWideCharsAndLen](getProcAddr, "string_new_with_wide_chars_and_len")
  if err != nil {
    return nil, err
  }

  iface.ptrStringOperatorIndex, err = callGetProcAddress[InterfaceStringOperatorIndex](getProcAddr, "string_operator_index")
  if err != nil {
    return nil, err
  }

  iface.ptrStringOperatorIndexConst, err = callGetProcAddress[InterfaceStringOperatorIndexConst](getProcAddr, "string_operator_index_const")
  if err != nil {
    return nil, err
  }

  iface.ptrStringOperatorPlusEqC32Str, err = callGetProcAddress[InterfaceStringOperatorPlusEqC32str](getProcAddr, "string_operator_plus_eq_c32str")
  if err != nil {
    return nil, err
  }

  iface.ptrStringOperatorPlusEqChar, err = callGetProcAddress[InterfaceStringOperatorPlusEqChar](getProcAddr, "string_operator_plus_eq_char")
  if err != nil {
    return nil, err
  }

  iface.ptrStringOperatorPlusEqCstr, err = callGetProcAddress[InterfaceStringOperatorPlusEqCstr](getProcAddr, "string_operator_plus_eq_cstr")
  if err != nil {
    return nil, err
  }

  iface.ptrStringOperatorPlusEqString, err = callGetProcAddress[InterfaceStringOperatorPlusEqString](getProcAddr, "string_operator_plus_eq_string")
  if err != nil {
    return nil, err
  }

  iface.ptrStringOperatorPlusEqWcstr, err = callGetProcAddress[InterfaceStringOperatorPlusEqWcstr](getProcAddr, "string_operator_plus_eq_wcstr")
  if err != nil {
    return nil, err
  }

  iface.ptrStringToLatin1Chars, err = callGetProcAddress[InterfaceStringToLatin1Chars](getProcAddr, "string_to_latin1_chars")
  if err != nil {
    return nil, err
  }

  iface.ptrStringToUtf16Chars, err = callGetProcAddress[InterfaceStringToUtf16Chars](getProcAddr, "string_to_utf16_chars")
  if err != nil {
    return nil, err
  }

  iface.ptrStringToUtf32Chars, err = callGetProcAddress[InterfaceStringToUtf32Chars](getProcAddr, "string_to_utf32_chars")
  if err != nil {
    return nil, err
  }

  iface.ptrStringToUtf8Chars, err = callGetProcAddress[InterfaceStringToUtf8Chars](getProcAddr, "string_to_utf8_chars")
  if err != nil {
    return nil, err
  }

  iface.ptrStringToWideChars, err = callGetProcAddress[InterfaceStringToWideChars](getProcAddr, "string_to_wide_chars")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantBooleanize, err = callGetProcAddress[InterfaceVariantBooleanize](getProcAddr, "variant_booleanize")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantCall, err = callGetProcAddress[InterfaceVariantCall](getProcAddr, "variant_call")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantCallStatic, err = callGetProcAddress[InterfaceVariantCallStatic](getProcAddr, "variant_call_static")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantCanConvert, err = callGetProcAddress[InterfaceVariantCanConvert](getProcAddr, "variant_can_convert")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantCanConvertStrict, err = callGetProcAddress[InterfaceVariantCanConvertStrict](getProcAddr, "variant_can_convert_strict")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantConstruct, err = callGetProcAddress[InterfaceVariantConstruct](getProcAddr, "variant_construct")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantDestroy, err = callGetProcAddress[InterfaceVariantDestroy](getProcAddr, "variant_destroy")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantDuplicate, err = callGetProcAddress[InterfaceVariantDuplicate](getProcAddr, "variant_duplicate")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantEvaluate, err = callGetProcAddress[InterfaceVariantEvaluate](getProcAddr, "variant_evaluate")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGet, err = callGetProcAddress[InterfaceVariantGet](getProcAddr, "variant_get")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetConstantValue, err = callGetProcAddress[InterfaceVariantGetConstantValue](getProcAddr, "variant_get_constant_value")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetIndexed, err = callGetProcAddress[InterfaceVariantGetIndexed](getProcAddr, "variant_get_indexed")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetKeyed, err = callGetProcAddress[InterfaceVariantGetKeyed](getProcAddr, "variant_get_keyed")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetNamed, err = callGetProcAddress[InterfaceVariantGetNamed](getProcAddr, "variant_get_named")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetPtrBuiltinMethod, err = callGetProcAddress[InterfaceVariantGetPtrBuiltinMethod](getProcAddr, "variant_get_ptr_builtin_method")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetPtrConstructor, err = callGetProcAddress[InterfaceVariantGetPtrConstructor](getProcAddr, "variant_get_ptr_constructor")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetPtrDestructor, err = callGetProcAddress[InterfaceVariantGetPtrDestructor](getProcAddr, "variant_get_ptr_destructor")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetPtrGetter, err = callGetProcAddress[InterfaceVariantGetPtrGetter](getProcAddr, "variant_get_ptr_getter")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetPtrIndexedGetter, err = callGetProcAddress[InterfaceVariantGetPtrIndexedGetter](getProcAddr, "variant_get_ptr_indexed_getter")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetPtrIndexedSetter, err = callGetProcAddress[InterfaceVariantGetPtrIndexedSetter](getProcAddr, "variant_get_ptr_indexed_setter")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetPtrKeyedChecker, err = callGetProcAddress[InterfaceVariantGetPtrKeyedChecker](getProcAddr, "variant_get_ptr_keyed_checker")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetPtrKeyedGetter, err = callGetProcAddress[InterfaceVariantGetPtrKeyedGetter](getProcAddr, "variant_get_ptr_keyed_getter")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetPtrKeyedSetter, err = callGetProcAddress[InterfaceVariantGetPtrKeyedSetter](getProcAddr, "variant_get_ptr_keyed_setter")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetPtrOperatorEvaluator, err = callGetProcAddress[InterfaceVariantGetPtrOperatorEvaluator](getProcAddr, "variant_get_ptr_operator_evaluator")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetPtrSetter, err = callGetProcAddress[InterfaceVariantGetPtrSetter](getProcAddr, "variant_get_ptr_setter")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetPtrUtilityFunction, err = callGetProcAddress[InterfaceVariantGetPtrUtilityFunction](getProcAddr, "variant_get_ptr_utility_function")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetType, err = callGetProcAddress[InterfaceVariantGetType](getProcAddr, "variant_get_type")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantGetTypeName, err = callGetProcAddress[InterfaceVariantGetTypeName](getProcAddr, "variant_get_type_name")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantHasKey, err = callGetProcAddress[InterfaceVariantHasKey](getProcAddr, "variant_has_key")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantHasMember, err = callGetProcAddress[InterfaceVariantHasMember](getProcAddr, "variant_has_member")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantHasMethod, err = callGetProcAddress[InterfaceVariantHasMethod](getProcAddr, "variant_has_method")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantHash, err = callGetProcAddress[InterfaceVariantHash](getProcAddr, "variant_hash")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantHashCompare, err = callGetProcAddress[InterfaceVariantHashCompare](getProcAddr, "variant_hash_compare")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantIterGet, err = callGetProcAddress[InterfaceVariantIterGet](getProcAddr, "variant_iter_get")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantIterInit, err = callGetProcAddress[InterfaceVariantIterInit](getProcAddr, "variant_iter_init")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantIterNext, err = callGetProcAddress[InterfaceVariantIterNext](getProcAddr, "variant_iter_next")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantNewCopy, err = callGetProcAddress[InterfaceVariantNewCopy](getProcAddr, "variant_new_copy")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantNewNil, err = callGetProcAddress[InterfaceVariantNewNil](getProcAddr, "variant_new_nil")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantRecursiveHash, err = callGetProcAddress[InterfaceVariantRecursiveHash](getProcAddr, "variant_recursive_hash")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantSet, err = callGetProcAddress[InterfaceVariantSet](getProcAddr, "variant_set")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantSetIndexed, err = callGetProcAddress[InterfaceVariantSetIndexed](getProcAddr, "variant_set_indexed")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantSetKeyed, err = callGetProcAddress[InterfaceVariantSetKeyed](getProcAddr, "variant_set_keyed")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantSetNamed, err = callGetProcAddress[InterfaceVariantSetNamed](getProcAddr, "variant_set_named")
  if err != nil {
    return nil, err
  }

  iface.ptrVariantStringify, err = callGetProcAddress[InterfaceVariantStringify](getProcAddr, "variant_stringify")
  if err != nil {
    return nil, err
  }

  iface.ptrWorkerThreadPoolAddNativeGroupTask, err = callGetProcAddress[InterfaceWorkerThreadPoolAddNativeGroupTask](getProcAddr, "worker_thread_pool_add_native_group_task")
  if err != nil {
    return nil, err
  }

  iface.ptrWorkerThreadPoolAddNativeTask, err = callGetProcAddress[InterfaceWorkerThreadPoolAddNativeTask](getProcAddr, "worker_thread_pool_add_native_task")
  if err != nil {
    return nil, err
  }

  iface.ptrXmlParserOpenBuffer, err = callGetProcAddress[InterfaceXmlParserOpenBuffer](getProcAddr, "xml_parser_open_buffer")
  if err != nil {
    return nil, err
  }

  return iface, nil
}

type interfaceImpl struct {
  ptrArrayOperatorIndex InterfaceArrayOperatorIndex
  ptrArrayOperatorIndexConst InterfaceArrayOperatorIndexConst
  ptrArrayRef InterfaceArrayRef
  ptrArraySetTyped InterfaceArraySetTyped
  ptrClassdbConstructObject InterfaceClassdbConstructObject
  ptrClassdbGetClassTag InterfaceClassdbGetClassTag
  ptrClassdbGetMethodBind InterfaceClassdbGetMethodBind
  ptrClassdbRegisterExtensionClass InterfaceClassdbRegisterExtensionClass
  ptrClassdbRegisterExtensionClassIntegerConstant InterfaceClassdbRegisterExtensionClassIntegerConstant
  ptrClassdbRegisterExtensionClassMethod InterfaceClassdbRegisterExtensionClassMethod
  ptrClassdbRegisterExtensionClassProperty InterfaceClassdbRegisterExtensionClassProperty
  ptrClassdbRegisterExtensionClassPropertyGroup InterfaceClassdbRegisterExtensionClassPropertyGroup
  ptrClassdbRegisterExtensionClassPropertySubgroup InterfaceClassdbRegisterExtensionClassPropertySubgroup
  ptrClassdbRegisterExtensionClassSignal InterfaceClassdbRegisterExtensionClassSignal
  ptrClassdbUnregisterExtensionClass InterfaceClassdbUnregisterExtensionClass
  ptrDictionaryOperatorIndex InterfaceDictionaryOperatorIndex
  ptrDictionaryOperatorIndexConst InterfaceDictionaryOperatorIndexConst
  ptrEditorAddPlugin InterfaceEditorAddPlugin
  ptrEditorRemovePlugin InterfaceEditorRemovePlugin
  ptrFileAccessGetBuffer InterfaceFileAccessGetBuffer
  ptrFileAccessStoreBuffer InterfaceFileAccessStoreBuffer
  ptrGetGodotVersion InterfaceGetGodotVersion
  ptrGetLibraryPath InterfaceGetLibraryPath
  ptrGetNativeStructSize InterfaceGetNativeStructSize
  ptrGetVariantFromTypeConstructor InterfaceGetVariantFromTypeConstructor
  ptrGetVariantToTypeConstructor InterfaceGetVariantToTypeConstructor
  ptrGlobalGetSingleton InterfaceGlobalGetSingleton
  ptrMemAlloc InterfaceMemAlloc
  ptrMemFree InterfaceMemFree
  ptrMemRealloc InterfaceMemRealloc
  ptrObjectCastTo InterfaceObjectCastTo
  ptrObjectDestroy InterfaceObjectDestroy
  ptrObjectGetClassName InterfaceObjectGetClassName
  ptrObjectGetInstanceBinding InterfaceObjectGetInstanceBinding
  ptrObjectGetInstanceFromId InterfaceObjectGetInstanceFromId
  ptrObjectGetInstanceId InterfaceObjectGetInstanceId
  ptrObjectMethodBindCall InterfaceObjectMethodBindCall
  ptrObjectMethodBindPtrcall InterfaceObjectMethodBindPtrcall
  ptrObjectSetInstance InterfaceObjectSetInstance
  ptrObjectSetInstanceBinding InterfaceObjectSetInstanceBinding
  ptrPackedByteArrayOperatorIndex InterfacePackedByteArrayOperatorIndex
  ptrPackedByteArrayOperatorIndexConst InterfacePackedByteArrayOperatorIndexConst
  ptrPackedColorArrayOperatorIndex InterfacePackedColorArrayOperatorIndex
  ptrPackedColorArrayOperatorIndexConst InterfacePackedColorArrayOperatorIndexConst
  ptrPackedFloat32ArrayOperatorIndex InterfacePackedFloat32ArrayOperatorIndex
  ptrPackedFloat32ArrayOperatorIndexConst InterfacePackedFloat32ArrayOperatorIndexConst
  ptrPackedFloat64ArrayOperatorIndex InterfacePackedFloat64ArrayOperatorIndex
  ptrPackedFloat64ArrayOperatorIndexConst InterfacePackedFloat64ArrayOperatorIndexConst
  ptrPackedInt32ArrayOperatorIndex InterfacePackedInt32ArrayOperatorIndex
  ptrPackedInt32ArrayOperatorIndexConst InterfacePackedInt32ArrayOperatorIndexConst
  ptrPackedInt64ArrayOperatorIndex InterfacePackedInt64ArrayOperatorIndex
  ptrPackedInt64ArrayOperatorIndexConst InterfacePackedInt64ArrayOperatorIndexConst
  ptrPackedStringArrayOperatorIndex InterfacePackedStringArrayOperatorIndex
  ptrPackedStringArrayOperatorIndexConst InterfacePackedStringArrayOperatorIndexConst
  ptrPackedVector2ArrayOperatorIndex InterfacePackedVector2ArrayOperatorIndex
  ptrPackedVector2ArrayOperatorIndexConst InterfacePackedVector2ArrayOperatorIndexConst
  ptrPackedVector3ArrayOperatorIndex InterfacePackedVector3ArrayOperatorIndex
  ptrPackedVector3ArrayOperatorIndexConst InterfacePackedVector3ArrayOperatorIndexConst
  ptrPrintError InterfacePrintError
  ptrPrintErrorWithMessage InterfacePrintErrorWithMessage
  ptrPrintScriptError InterfacePrintScriptError
  ptrPrintScriptErrorWithMessage InterfacePrintScriptErrorWithMessage
  ptrPrintWarning InterfacePrintWarning
  ptrPrintWarningWithMessage InterfacePrintWarningWithMessage
  ptrRefGetObject InterfaceRefGetObject
  ptrRefSetObject InterfaceRefSetObject
  ptrScriptInstanceCreate InterfaceScriptInstanceCreate
  ptrStringNewWithLatin1Chars InterfaceStringNewWithLatin1Chars
  ptrStringNewWithLatin1CharsAndLen InterfaceStringNewWithLatin1CharsAndLen
  ptrStringNewWithUtf16Chars InterfaceStringNewWithUtf16Chars
  ptrStringNewWithUtf16CharsAndLen InterfaceStringNewWithUtf16CharsAndLen
  ptrStringNewWithUtf32Chars InterfaceStringNewWithUtf32Chars
  ptrStringNewWithUtf32CharsAndLen InterfaceStringNewWithUtf32CharsAndLen
  ptrStringNewWithUtf8Chars InterfaceStringNewWithUtf8Chars
  ptrStringNewWithUtf8CharsAndLen InterfaceStringNewWithUtf8CharsAndLen
  ptrStringNewWithWideChars InterfaceStringNewWithWideChars
  ptrStringNewWithWideCharsAndLen InterfaceStringNewWithWideCharsAndLen
  ptrStringOperatorIndex InterfaceStringOperatorIndex
  ptrStringOperatorIndexConst InterfaceStringOperatorIndexConst
  ptrStringOperatorPlusEqC32Str InterfaceStringOperatorPlusEqC32str
  ptrStringOperatorPlusEqChar InterfaceStringOperatorPlusEqChar
  ptrStringOperatorPlusEqCstr InterfaceStringOperatorPlusEqCstr
  ptrStringOperatorPlusEqString InterfaceStringOperatorPlusEqString
  ptrStringOperatorPlusEqWcstr InterfaceStringOperatorPlusEqWcstr
  ptrStringToLatin1Chars InterfaceStringToLatin1Chars
  ptrStringToUtf16Chars InterfaceStringToUtf16Chars
  ptrStringToUtf32Chars InterfaceStringToUtf32Chars
  ptrStringToUtf8Chars InterfaceStringToUtf8Chars
  ptrStringToWideChars InterfaceStringToWideChars
  ptrVariantBooleanize InterfaceVariantBooleanize
  ptrVariantCall InterfaceVariantCall
  ptrVariantCallStatic InterfaceVariantCallStatic
  ptrVariantCanConvert InterfaceVariantCanConvert
  ptrVariantCanConvertStrict InterfaceVariantCanConvertStrict
  ptrVariantConstruct InterfaceVariantConstruct
  ptrVariantDestroy InterfaceVariantDestroy
  ptrVariantDuplicate InterfaceVariantDuplicate
  ptrVariantEvaluate InterfaceVariantEvaluate
  ptrVariantGet InterfaceVariantGet
  ptrVariantGetConstantValue InterfaceVariantGetConstantValue
  ptrVariantGetIndexed InterfaceVariantGetIndexed
  ptrVariantGetKeyed InterfaceVariantGetKeyed
  ptrVariantGetNamed InterfaceVariantGetNamed
  ptrVariantGetPtrBuiltinMethod InterfaceVariantGetPtrBuiltinMethod
  ptrVariantGetPtrConstructor InterfaceVariantGetPtrConstructor
  ptrVariantGetPtrDestructor InterfaceVariantGetPtrDestructor
  ptrVariantGetPtrGetter InterfaceVariantGetPtrGetter
  ptrVariantGetPtrIndexedGetter InterfaceVariantGetPtrIndexedGetter
  ptrVariantGetPtrIndexedSetter InterfaceVariantGetPtrIndexedSetter
  ptrVariantGetPtrKeyedChecker InterfaceVariantGetPtrKeyedChecker
  ptrVariantGetPtrKeyedGetter InterfaceVariantGetPtrKeyedGetter
  ptrVariantGetPtrKeyedSetter InterfaceVariantGetPtrKeyedSetter
  ptrVariantGetPtrOperatorEvaluator InterfaceVariantGetPtrOperatorEvaluator
  ptrVariantGetPtrSetter InterfaceVariantGetPtrSetter
  ptrVariantGetPtrUtilityFunction InterfaceVariantGetPtrUtilityFunction
  ptrVariantGetType InterfaceVariantGetType
  ptrVariantGetTypeName InterfaceVariantGetTypeName
  ptrVariantHasKey InterfaceVariantHasKey
  ptrVariantHasMember InterfaceVariantHasMember
  ptrVariantHasMethod InterfaceVariantHasMethod
  ptrVariantHash InterfaceVariantHash
  ptrVariantHashCompare InterfaceVariantHashCompare
  ptrVariantIterGet InterfaceVariantIterGet
  ptrVariantIterInit InterfaceVariantIterInit
  ptrVariantIterNext InterfaceVariantIterNext
  ptrVariantNewCopy InterfaceVariantNewCopy
  ptrVariantNewNil InterfaceVariantNewNil
  ptrVariantRecursiveHash InterfaceVariantRecursiveHash
  ptrVariantSet InterfaceVariantSet
  ptrVariantSetIndexed InterfaceVariantSetIndexed
  ptrVariantSetKeyed InterfaceVariantSetKeyed
  ptrVariantSetNamed InterfaceVariantSetNamed
  ptrVariantStringify InterfaceVariantStringify
  ptrWorkerThreadPoolAddNativeGroupTask InterfaceWorkerThreadPoolAddNativeGroupTask
  ptrWorkerThreadPoolAddNativeTask InterfaceWorkerThreadPoolAddNativeTask
  ptrXmlParserOpenBuffer InterfaceXmlParserOpenBuffer
}

func (me *interfaceImpl) ArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) VariantPtr {
  return C.callArrayOperatorIndex(me.ptrArrayOperatorIndex, pSelf, pIndex,)
}

func (me *interfaceImpl) ArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) VariantPtr {
  return C.callArrayOperatorIndexConst(me.ptrArrayOperatorIndexConst, pSelf, pIndex,)
}

func (me *interfaceImpl) ArrayRef(pSelf TypePtr, pFrom ConstTypePtr, )  {
  C.callArrayRef(me.ptrArrayRef, pSelf, pFrom,)
}

func (me *interfaceImpl) ArraySetTyped(pSelf TypePtr, pType VariantType, pClassName ConstStringNamePtr, pScript ConstVariantPtr, )  {
  C.callArraySetTyped(me.ptrArraySetTyped, pSelf, pType, pClassName, pScript,)
}

func (me *interfaceImpl) ClassdbConstructObject(pClassname ConstStringNamePtr, ) ObjectPtr {
  return C.callClassdbConstructObject(me.ptrClassdbConstructObject, pClassname,)
}

func (me *interfaceImpl) ClassdbGetClassTag(pClassname ConstStringNamePtr, ) unsafe.Pointer {
  return C.callClassdbGetClassTag(me.ptrClassdbGetClassTag, pClassname,)
}

func (me *interfaceImpl) ClassdbGetMethodBind(pClassname ConstStringNamePtr, pMethodname ConstStringNamePtr, pHash Int, ) MethodBindPtr {
  return C.callClassdbGetMethodBind(me.ptrClassdbGetMethodBind, pClassname, pMethodname, pHash,)
}

func (me *interfaceImpl) ClassdbRegisterExtensionClass(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, pParentClassName ConstStringNamePtr, pExtensionFuncs *ClassCreationInfo, )  {
  C.callClassdbRegisterExtensionClass(me.ptrClassdbRegisterExtensionClass, pLibrary, pClassName, pParentClassName, pExtensionFuncs,)
}

func (me *interfaceImpl) ClassdbRegisterExtensionClassIntegerConstant(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, pEnumName ConstStringNamePtr, pConstantName ConstStringNamePtr, pConstantValue Int, pIsBitfield Bool, )  {
  C.callClassdbRegisterExtensionClassIntegerConstant(me.ptrClassdbRegisterExtensionClassIntegerConstant, pLibrary, pClassName, pEnumName, pConstantName, pConstantValue, pIsBitfield,)
}

func (me *interfaceImpl) ClassdbRegisterExtensionClassMethod(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, pMethodInfo *ClassMethodInfo, )  {
  C.callClassdbRegisterExtensionClassMethod(me.ptrClassdbRegisterExtensionClassMethod, pLibrary, pClassName, pMethodInfo,)
}

func (me *interfaceImpl) ClassdbRegisterExtensionClassProperty(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, pInfo *PropertyInfo, pSetter ConstStringNamePtr, pGetter ConstStringNamePtr, )  {
  C.callClassdbRegisterExtensionClassProperty(me.ptrClassdbRegisterExtensionClassProperty, pLibrary, pClassName, pInfo, pSetter, pGetter,)
}

func (me *interfaceImpl) ClassdbRegisterExtensionClassPropertyGroup(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, pGroupName ConstStringPtr, pPrefix ConstStringPtr, )  {
  C.callClassdbRegisterExtensionClassPropertyGroup(me.ptrClassdbRegisterExtensionClassPropertyGroup, pLibrary, pClassName, pGroupName, pPrefix,)
}

func (me *interfaceImpl) ClassdbRegisterExtensionClassPropertySubgroup(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, pSubgroupName ConstStringPtr, pPrefix ConstStringPtr, )  {
  C.callClassdbRegisterExtensionClassPropertySubgroup(me.ptrClassdbRegisterExtensionClassPropertySubgroup, pLibrary, pClassName, pSubgroupName, pPrefix,)
}

func (me *interfaceImpl) ClassdbRegisterExtensionClassSignal(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, pSignalName ConstStringNamePtr, pArgumentInfo *PropertyInfo, pArgumentCount Int, )  {
  C.callClassdbRegisterExtensionClassSignal(me.ptrClassdbRegisterExtensionClassSignal, pLibrary, pClassName, pSignalName, pArgumentInfo, pArgumentCount,)
}

func (me *interfaceImpl) ClassdbUnregisterExtensionClass(pLibrary ClassLibraryPtr, pClassName ConstStringNamePtr, )  {
  C.callClassdbUnregisterExtensionClass(me.ptrClassdbUnregisterExtensionClass, pLibrary, pClassName,)
}

func (me *interfaceImpl) DictionaryOperatorIndex(pSelf TypePtr, pKey ConstVariantPtr, ) VariantPtr {
  return C.callDictionaryOperatorIndex(me.ptrDictionaryOperatorIndex, pSelf, pKey,)
}

func (me *interfaceImpl) DictionaryOperatorIndexConst(pSelf ConstTypePtr, pKey ConstVariantPtr, ) VariantPtr {
  return C.callDictionaryOperatorIndexConst(me.ptrDictionaryOperatorIndexConst, pSelf, pKey,)
}

func (me *interfaceImpl) EditorAddPlugin(pClassName ConstStringNamePtr, )  {
  C.callEditorAddPlugin(me.ptrEditorAddPlugin, pClassName,)
}

func (me *interfaceImpl) EditorRemovePlugin(pClassName ConstStringNamePtr, )  {
  C.callEditorRemovePlugin(me.ptrEditorRemovePlugin, pClassName,)
}

func (me *interfaceImpl) FileAccessGetBuffer(pInstance ConstObjectPtr, pDst *uint8, pLength uint64, ) uint64 {
  return C.callFileAccessGetBuffer(me.ptrFileAccessGetBuffer, pInstance, pDst, pLength,)
}

func (me *interfaceImpl) FileAccessStoreBuffer(pInstance ObjectPtr, pSrc *uint8, pLength uint64, )  {
  C.callFileAccessStoreBuffer(me.ptrFileAccessStoreBuffer, pInstance, pSrc, pLength,)
}

func (me *interfaceImpl) GetGodotVersion(rGodotVersion *GodotVersion, )  {
  C.callGetGodotVersion(me.ptrGetGodotVersion, rGodotVersion,)
}

func (me *interfaceImpl) GetLibraryPath(pLibrary ClassLibraryPtr, rPath UninitializedStringPtr, )  {
  C.callGetLibraryPath(me.ptrGetLibraryPath, pLibrary, rPath,)
}

func (me *interfaceImpl) GetNativeStructSize(pName ConstStringNamePtr, ) uint64 {
  return C.callGetNativeStructSize(me.ptrGetNativeStructSize, pName,)
}

func (me *interfaceImpl) GetVariantFromTypeConstructor(pType VariantType, ) VariantFromTypeConstructorFunc {
  return C.callGetVariantFromTypeConstructor(me.ptrGetVariantFromTypeConstructor, pType,)
}

func (me *interfaceImpl) GetVariantToTypeConstructor(pType VariantType, ) TypeFromVariantConstructorFunc {
  return C.callGetVariantToTypeConstructor(me.ptrGetVariantToTypeConstructor, pType,)
}

func (me *interfaceImpl) GlobalGetSingleton(pName ConstStringNamePtr, ) ObjectPtr {
  return C.callGlobalGetSingleton(me.ptrGlobalGetSingleton, pName,)
}

func (me *interfaceImpl) MemAlloc(pBytes uint64, ) unsafe.Pointer {
  return C.callMemAlloc(me.ptrMemAlloc, pBytes,)
}

func (me *interfaceImpl) MemFree(pPtr unsafe.Pointer, )  {
  C.callMemFree(me.ptrMemFree, pPtr,)
}

func (me *interfaceImpl) MemRealloc(pPtr unsafe.Pointer, pBytes uint64, ) unsafe.Pointer {
  return C.callMemRealloc(me.ptrMemRealloc, pPtr, pBytes,)
}

func (me *interfaceImpl) ObjectCastTo(pObject ConstObjectPtr, pClassTag unsafe.Pointer, ) ObjectPtr {
  return C.callObjectCastTo(me.ptrObjectCastTo, pObject, pClassTag,)
}

func (me *interfaceImpl) ObjectDestroy(pO ObjectPtr, )  {
  C.callObjectDestroy(me.ptrObjectDestroy, pO,)
}

func (me *interfaceImpl) ObjectGetClassName(pObject ConstObjectPtr, pLibrary ClassLibraryPtr, rClassName UninitializedStringNamePtr, ) Bool {
  return C.callObjectGetClassName(me.ptrObjectGetClassName, pObject, pLibrary, rClassName,)
}

func (me *interfaceImpl) ObjectGetInstanceBinding(pO ObjectPtr, pToken unsafe.Pointer, pCallbacks *InstanceBindingCallbacks, ) unsafe.Pointer {
  return C.callObjectGetInstanceBinding(me.ptrObjectGetInstanceBinding, pO, pToken, pCallbacks,)
}

func (me *interfaceImpl) ObjectGetInstanceFromId(pInstanceId uint64, ) ObjectPtr {
  return C.callObjectGetInstanceFromId(me.ptrObjectGetInstanceFromId, pInstanceId,)
}

func (me *interfaceImpl) ObjectGetInstanceId(pObject ConstObjectPtr, ) uint64 {
  return C.callObjectGetInstanceId(me.ptrObjectGetInstanceId, pObject,)
}

func (me *interfaceImpl) ObjectMethodBindCall(pMethodBind MethodBindPtr, pInstance ObjectPtr, pArgs *ConstVariantPtr, pArgCount Int, rRet UninitializedVariantPtr, rError *CallError, )  {
  C.callObjectMethodBindCall(me.ptrObjectMethodBindCall, pMethodBind, pInstance, pArgs, pArgCount, rRet, rError,)
}

func (me *interfaceImpl) ObjectMethodBindPtrcall(pMethodBind MethodBindPtr, pInstance ObjectPtr, pArgs *ConstTypePtr, rRet TypePtr, )  {
  C.callObjectMethodBindPtrcall(me.ptrObjectMethodBindPtrcall, pMethodBind, pInstance, pArgs, rRet,)
}

func (me *interfaceImpl) ObjectSetInstance(pO ObjectPtr, pClassname ConstStringNamePtr, pInstance ClassInstancePtr, )  {
  C.callObjectSetInstance(me.ptrObjectSetInstance, pO, pClassname, pInstance,)
}

func (me *interfaceImpl) ObjectSetInstanceBinding(pO ObjectPtr, pToken unsafe.Pointer, pBinding unsafe.Pointer, pCallbacks *InstanceBindingCallbacks, )  {
  C.callObjectSetInstanceBinding(me.ptrObjectSetInstanceBinding, pO, pToken, pBinding, pCallbacks,)
}

func (me *interfaceImpl) PackedByteArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) *uint8 {
  return C.callPackedByteArrayOperatorIndex(me.ptrPackedByteArrayOperatorIndex, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedByteArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) *uint8 {
  return C.callPackedByteArrayOperatorIndexConst(me.ptrPackedByteArrayOperatorIndexConst, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedColorArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) TypePtr {
  return C.callPackedColorArrayOperatorIndex(me.ptrPackedColorArrayOperatorIndex, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedColorArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) TypePtr {
  return C.callPackedColorArrayOperatorIndexConst(me.ptrPackedColorArrayOperatorIndexConst, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedFloat32ArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) *float32 {
  return C.callPackedFloat32ArrayOperatorIndex(me.ptrPackedFloat32ArrayOperatorIndex, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedFloat32ArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) *float32 {
  return C.callPackedFloat32ArrayOperatorIndexConst(me.ptrPackedFloat32ArrayOperatorIndexConst, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedFloat64ArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) *float64 {
  return C.callPackedFloat64ArrayOperatorIndex(me.ptrPackedFloat64ArrayOperatorIndex, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedFloat64ArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) *float64 {
  return C.callPackedFloat64ArrayOperatorIndexConst(me.ptrPackedFloat64ArrayOperatorIndexConst, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedInt32ArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) *int {
  return C.callPackedInt32ArrayOperatorIndex(me.ptrPackedInt32ArrayOperatorIndex, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedInt32ArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) *int {
  return C.callPackedInt32ArrayOperatorIndexConst(me.ptrPackedInt32ArrayOperatorIndexConst, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedInt64ArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) *int64 {
  return C.callPackedInt64ArrayOperatorIndex(me.ptrPackedInt64ArrayOperatorIndex, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedInt64ArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) *int64 {
  return C.callPackedInt64ArrayOperatorIndexConst(me.ptrPackedInt64ArrayOperatorIndexConst, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedStringArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) StringPtr {
  return C.callPackedStringArrayOperatorIndex(me.ptrPackedStringArrayOperatorIndex, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedStringArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) StringPtr {
  return C.callPackedStringArrayOperatorIndexConst(me.ptrPackedStringArrayOperatorIndexConst, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedVector2ArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) TypePtr {
  return C.callPackedVector2ArrayOperatorIndex(me.ptrPackedVector2ArrayOperatorIndex, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedVector2ArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) TypePtr {
  return C.callPackedVector2ArrayOperatorIndexConst(me.ptrPackedVector2ArrayOperatorIndexConst, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedVector3ArrayOperatorIndex(pSelf TypePtr, pIndex Int, ) TypePtr {
  return C.callPackedVector3ArrayOperatorIndex(me.ptrPackedVector3ArrayOperatorIndex, pSelf, pIndex,)
}

func (me *interfaceImpl) PackedVector3ArrayOperatorIndexConst(pSelf ConstTypePtr, pIndex Int, ) TypePtr {
  return C.callPackedVector3ArrayOperatorIndexConst(me.ptrPackedVector3ArrayOperatorIndexConst, pSelf, pIndex,)
}

func (me *interfaceImpl) PrintError(pDescription string, pFunction string, pFile string, pLine int, pEditorNotify Bool, )  {
  C.callPrintError(me.ptrPrintError, pDescription, pFunction, pFile, pLine, pEditorNotify,)
}

func (me *interfaceImpl) PrintErrorWithMessage(pDescription string, pMessage string, pFunction string, pFile string, pLine int, pEditorNotify Bool, )  {
  C.callPrintErrorWithMessage(me.ptrPrintErrorWithMessage, pDescription, pMessage, pFunction, pFile, pLine, pEditorNotify,)
}

func (me *interfaceImpl) PrintScriptError(pDescription string, pFunction string, pFile string, pLine int, pEditorNotify Bool, )  {
  C.callPrintScriptError(me.ptrPrintScriptError, pDescription, pFunction, pFile, pLine, pEditorNotify,)
}

func (me *interfaceImpl) PrintScriptErrorWithMessage(pDescription string, pMessage string, pFunction string, pFile string, pLine int, pEditorNotify Bool, )  {
  C.callPrintScriptErrorWithMessage(me.ptrPrintScriptErrorWithMessage, pDescription, pMessage, pFunction, pFile, pLine, pEditorNotify,)
}

func (me *interfaceImpl) PrintWarning(pDescription string, pFunction string, pFile string, pLine int, pEditorNotify Bool, )  {
  C.callPrintWarning(me.ptrPrintWarning, pDescription, pFunction, pFile, pLine, pEditorNotify,)
}

func (me *interfaceImpl) PrintWarningWithMessage(pDescription string, pMessage string, pFunction string, pFile string, pLine int, pEditorNotify Bool, )  {
  C.callPrintWarningWithMessage(me.ptrPrintWarningWithMessage, pDescription, pMessage, pFunction, pFile, pLine, pEditorNotify,)
}

func (me *interfaceImpl) RefGetObject(pRef ConstRefPtr, ) ObjectPtr {
  return C.callRefGetObject(me.ptrRefGetObject, pRef,)
}

func (me *interfaceImpl) RefSetObject(pRef RefPtr, pObject ObjectPtr, )  {
  C.callRefSetObject(me.ptrRefSetObject, pRef, pObject,)
}

func (me *interfaceImpl) ScriptInstanceCreate(pInfo *ScriptInstanceInfo, pInstanceData ScriptInstanceDataPtr, ) ScriptInstancePtr {
  return C.callScriptInstanceCreate(me.ptrScriptInstanceCreate, pInfo, pInstanceData,)
}

func (me *interfaceImpl) StringNewWithLatin1Chars(rDest UninitializedStringPtr, pContents string, )  {
  C.callStringNewWithLatin1Chars(me.ptrStringNewWithLatin1Chars, rDest, pContents,)
}

func (me *interfaceImpl) StringNewWithLatin1CharsAndLen(rDest UninitializedStringPtr, pContents string, pSize Int, )  {
  C.callStringNewWithLatin1CharsAndLen(me.ptrStringNewWithLatin1CharsAndLen, rDest, pContents, pSize,)
}

func (me *interfaceImpl) StringNewWithUtf16Chars(rDest UninitializedStringPtr, pContents *uint16, )  {
  C.callStringNewWithUtf16Chars(me.ptrStringNewWithUtf16Chars, rDest, pContents,)
}

func (me *interfaceImpl) StringNewWithUtf16CharsAndLen(rDest UninitializedStringPtr, pContents *uint16, pSize Int, )  {
  C.callStringNewWithUtf16CharsAndLen(me.ptrStringNewWithUtf16CharsAndLen, rDest, pContents, pSize,)
}

func (me *interfaceImpl) StringNewWithUtf32Chars(rDest UninitializedStringPtr, pContents *uint, )  {
  C.callStringNewWithUtf32Chars(me.ptrStringNewWithUtf32Chars, rDest, pContents,)
}

func (me *interfaceImpl) StringNewWithUtf32CharsAndLen(rDest UninitializedStringPtr, pContents *uint, pSize Int, )  {
  C.callStringNewWithUtf32CharsAndLen(me.ptrStringNewWithUtf32CharsAndLen, rDest, pContents, pSize,)
}

func (me *interfaceImpl) StringNewWithUtf8Chars(rDest UninitializedStringPtr, pContents string, )  {
  C.callStringNewWithUtf8Chars(me.ptrStringNewWithUtf8Chars, rDest, pContents,)
}

func (me *interfaceImpl) StringNewWithUtf8CharsAndLen(rDest UninitializedStringPtr, pContents string, pSize Int, )  {
  C.callStringNewWithUtf8CharsAndLen(me.ptrStringNewWithUtf8CharsAndLen, rDest, pContents, pSize,)
}

func (me *interfaceImpl) StringNewWithWideChars(rDest UninitializedStringPtr, pContents *int, )  {
  C.callStringNewWithWideChars(me.ptrStringNewWithWideChars, rDest, pContents,)
}

func (me *interfaceImpl) StringNewWithWideCharsAndLen(rDest UninitializedStringPtr, pContents *int, pSize Int, )  {
  C.callStringNewWithWideCharsAndLen(me.ptrStringNewWithWideCharsAndLen, rDest, pContents, pSize,)
}

func (me *interfaceImpl) StringOperatorIndex(pSelf StringPtr, pIndex Int, ) *uint {
  return C.callStringOperatorIndex(me.ptrStringOperatorIndex, pSelf, pIndex,)
}

func (me *interfaceImpl) StringOperatorIndexConst(pSelf ConstStringPtr, pIndex Int, ) *uint {
  return C.callStringOperatorIndexConst(me.ptrStringOperatorIndexConst, pSelf, pIndex,)
}

func (me *interfaceImpl) StringOperatorPlusEqC32Str(pSelf StringPtr, pB *uint, )  {
  C.callStringOperatorPlusEqC32Str(me.ptrStringOperatorPlusEqC32Str, pSelf, pB,)
}

func (me *interfaceImpl) StringOperatorPlusEqChar(pSelf StringPtr, pB uint, )  {
  C.callStringOperatorPlusEqChar(me.ptrStringOperatorPlusEqChar, pSelf, pB,)
}

func (me *interfaceImpl) StringOperatorPlusEqCstr(pSelf StringPtr, pB string, )  {
  C.callStringOperatorPlusEqCstr(me.ptrStringOperatorPlusEqCstr, pSelf, pB,)
}

func (me *interfaceImpl) StringOperatorPlusEqString(pSelf StringPtr, pB ConstStringPtr, )  {
  C.callStringOperatorPlusEqString(me.ptrStringOperatorPlusEqString, pSelf, pB,)
}

func (me *interfaceImpl) StringOperatorPlusEqWcstr(pSelf StringPtr, pB *int, )  {
  C.callStringOperatorPlusEqWcstr(me.ptrStringOperatorPlusEqWcstr, pSelf, pB,)
}

func (me *interfaceImpl) StringToLatin1Chars(pSelf ConstStringPtr, rText string, pMaxWriteLength Int, ) Int {
  return C.callStringToLatin1Chars(me.ptrStringToLatin1Chars, pSelf, rText, pMaxWriteLength,)
}

func (me *interfaceImpl) StringToUtf16Chars(pSelf ConstStringPtr, rText *uint16, pMaxWriteLength Int, ) Int {
  return C.callStringToUtf16Chars(me.ptrStringToUtf16Chars, pSelf, rText, pMaxWriteLength,)
}

func (me *interfaceImpl) StringToUtf32Chars(pSelf ConstStringPtr, rText *uint, pMaxWriteLength Int, ) Int {
  return C.callStringToUtf32Chars(me.ptrStringToUtf32Chars, pSelf, rText, pMaxWriteLength,)
}

func (me *interfaceImpl) StringToUtf8Chars(pSelf ConstStringPtr, rText string, pMaxWriteLength Int, ) Int {
  return C.callStringToUtf8Chars(me.ptrStringToUtf8Chars, pSelf, rText, pMaxWriteLength,)
}

func (me *interfaceImpl) StringToWideChars(pSelf ConstStringPtr, rText *int, pMaxWriteLength Int, ) Int {
  return C.callStringToWideChars(me.ptrStringToWideChars, pSelf, rText, pMaxWriteLength,)
}

func (me *interfaceImpl) VariantBooleanize(pSelf ConstVariantPtr, ) Bool {
  return C.callVariantBooleanize(me.ptrVariantBooleanize, pSelf,)
}

func (me *interfaceImpl) VariantCall(pSelf VariantPtr, pMethod ConstStringNamePtr, pArgs *ConstVariantPtr, pArgumentCount Int, rReturn UninitializedVariantPtr, rError *CallError, )  {
  C.callVariantCall(me.ptrVariantCall, pSelf, pMethod, pArgs, pArgumentCount, rReturn, rError,)
}

func (me *interfaceImpl) VariantCallStatic(pType VariantType, pMethod ConstStringNamePtr, pArgs *ConstVariantPtr, pArgumentCount Int, rReturn UninitializedVariantPtr, rError *CallError, )  {
  C.callVariantCallStatic(me.ptrVariantCallStatic, pType, pMethod, pArgs, pArgumentCount, rReturn, rError,)
}

func (me *interfaceImpl) VariantCanConvert(pFrom VariantType, pTo VariantType, ) Bool {
  return C.callVariantCanConvert(me.ptrVariantCanConvert, pFrom, pTo,)
}

func (me *interfaceImpl) VariantCanConvertStrict(pFrom VariantType, pTo VariantType, ) Bool {
  return C.callVariantCanConvertStrict(me.ptrVariantCanConvertStrict, pFrom, pTo,)
}

func (me *interfaceImpl) VariantConstruct(pType VariantType, rBase UninitializedVariantPtr, pArgs *ConstVariantPtr, pArgumentCount int, rError *CallError, )  {
  C.callVariantConstruct(me.ptrVariantConstruct, pType, rBase, pArgs, pArgumentCount, rError,)
}

func (me *interfaceImpl) VariantDestroy(pSelf VariantPtr, )  {
  C.callVariantDestroy(me.ptrVariantDestroy, pSelf,)
}

func (me *interfaceImpl) VariantDuplicate(pSelf ConstVariantPtr, rRet VariantPtr, pDeep Bool, )  {
  C.callVariantDuplicate(me.ptrVariantDuplicate, pSelf, rRet, pDeep,)
}

func (me *interfaceImpl) VariantEvaluate(pOp VariantOperator, pA ConstVariantPtr, pB ConstVariantPtr, rReturn UninitializedVariantPtr, rValid *uint8, )  {
  C.callVariantEvaluate(me.ptrVariantEvaluate, pOp, pA, pB, rReturn, rValid,)
}

func (me *interfaceImpl) VariantGet(pSelf ConstVariantPtr, pKey ConstVariantPtr, rRet UninitializedVariantPtr, rValid *uint8, )  {
  C.callVariantGet(me.ptrVariantGet, pSelf, pKey, rRet, rValid,)
}

func (me *interfaceImpl) VariantGetConstantValue(pType VariantType, pConstant ConstStringNamePtr, rRet UninitializedVariantPtr, )  {
  C.callVariantGetConstantValue(me.ptrVariantGetConstantValue, pType, pConstant, rRet,)
}

func (me *interfaceImpl) VariantGetIndexed(pSelf ConstVariantPtr, pIndex Int, rRet UninitializedVariantPtr, rValid *uint8, rOob *uint8, )  {
  C.callVariantGetIndexed(me.ptrVariantGetIndexed, pSelf, pIndex, rRet, rValid, rOob,)
}

func (me *interfaceImpl) VariantGetKeyed(pSelf ConstVariantPtr, pKey ConstVariantPtr, rRet UninitializedVariantPtr, rValid *uint8, )  {
  C.callVariantGetKeyed(me.ptrVariantGetKeyed, pSelf, pKey, rRet, rValid,)
}

func (me *interfaceImpl) VariantGetNamed(pSelf ConstVariantPtr, pKey ConstStringNamePtr, rRet UninitializedVariantPtr, rValid *uint8, )  {
  C.callVariantGetNamed(me.ptrVariantGetNamed, pSelf, pKey, rRet, rValid,)
}

func (me *interfaceImpl) VariantGetPtrBuiltinMethod(pType VariantType, pMethod ConstStringNamePtr, pHash Int, ) PtrBuiltInMethod {
  return C.callVariantGetPtrBuiltinMethod(me.ptrVariantGetPtrBuiltinMethod, pType, pMethod, pHash,)
}

func (me *interfaceImpl) VariantGetPtrConstructor(pType VariantType, pConstructor int, ) PtrConstructor {
  return C.callVariantGetPtrConstructor(me.ptrVariantGetPtrConstructor, pType, pConstructor,)
}

func (me *interfaceImpl) VariantGetPtrDestructor(pType VariantType, ) PtrDestructor {
  return C.callVariantGetPtrDestructor(me.ptrVariantGetPtrDestructor, pType,)
}

func (me *interfaceImpl) VariantGetPtrGetter(pType VariantType, pMember ConstStringNamePtr, ) PtrGetter {
  return C.callVariantGetPtrGetter(me.ptrVariantGetPtrGetter, pType, pMember,)
}

func (me *interfaceImpl) VariantGetPtrIndexedGetter(pType VariantType, ) PtrIndexedGetter {
  return C.callVariantGetPtrIndexedGetter(me.ptrVariantGetPtrIndexedGetter, pType,)
}

func (me *interfaceImpl) VariantGetPtrIndexedSetter(pType VariantType, ) PtrIndexedSetter {
  return C.callVariantGetPtrIndexedSetter(me.ptrVariantGetPtrIndexedSetter, pType,)
}

func (me *interfaceImpl) VariantGetPtrKeyedChecker(pType VariantType, ) PtrKeyedChecker {
  return C.callVariantGetPtrKeyedChecker(me.ptrVariantGetPtrKeyedChecker, pType,)
}

func (me *interfaceImpl) VariantGetPtrKeyedGetter(pType VariantType, ) PtrKeyedGetter {
  return C.callVariantGetPtrKeyedGetter(me.ptrVariantGetPtrKeyedGetter, pType,)
}

func (me *interfaceImpl) VariantGetPtrKeyedSetter(pType VariantType, ) PtrKeyedSetter {
  return C.callVariantGetPtrKeyedSetter(me.ptrVariantGetPtrKeyedSetter, pType,)
}

func (me *interfaceImpl) VariantGetPtrOperatorEvaluator(pOperator VariantOperator, pTypeA VariantType, pTypeB VariantType, ) PtrOperatorEvaluator {
  return C.callVariantGetPtrOperatorEvaluator(me.ptrVariantGetPtrOperatorEvaluator, pOperator, pTypeA, pTypeB,)
}

func (me *interfaceImpl) VariantGetPtrSetter(pType VariantType, pMember ConstStringNamePtr, ) PtrSetter {
  return C.callVariantGetPtrSetter(me.ptrVariantGetPtrSetter, pType, pMember,)
}

func (me *interfaceImpl) VariantGetPtrUtilityFunction(pFunction ConstStringNamePtr, pHash Int, ) PtrUtilityFunction {
  return C.callVariantGetPtrUtilityFunction(me.ptrVariantGetPtrUtilityFunction, pFunction, pHash,)
}

func (me *interfaceImpl) VariantGetType(pSelf ConstVariantPtr, ) VariantType {
  return C.callVariantGetType(me.ptrVariantGetType, pSelf,)
}

func (me *interfaceImpl) VariantGetTypeName(pType VariantType, rName UninitializedStringPtr, )  {
  C.callVariantGetTypeName(me.ptrVariantGetTypeName, pType, rName,)
}

func (me *interfaceImpl) VariantHasKey(pSelf ConstVariantPtr, pKey ConstVariantPtr, rValid *uint8, ) Bool {
  return C.callVariantHasKey(me.ptrVariantHasKey, pSelf, pKey, rValid,)
}

func (me *interfaceImpl) VariantHasMember(pType VariantType, pMember ConstStringNamePtr, ) Bool {
  return C.callVariantHasMember(me.ptrVariantHasMember, pType, pMember,)
}

func (me *interfaceImpl) VariantHasMethod(pSelf ConstVariantPtr, pMethod ConstStringNamePtr, ) Bool {
  return C.callVariantHasMethod(me.ptrVariantHasMethod, pSelf, pMethod,)
}

func (me *interfaceImpl) VariantHash(pSelf ConstVariantPtr, ) Int {
  return C.callVariantHash(me.ptrVariantHash, pSelf,)
}

func (me *interfaceImpl) VariantHashCompare(pSelf ConstVariantPtr, pOther ConstVariantPtr, ) Bool {
  return C.callVariantHashCompare(me.ptrVariantHashCompare, pSelf, pOther,)
}

func (me *interfaceImpl) VariantIterGet(pSelf ConstVariantPtr, rIter VariantPtr, rRet UninitializedVariantPtr, rValid *uint8, )  {
  C.callVariantIterGet(me.ptrVariantIterGet, pSelf, rIter, rRet, rValid,)
}

func (me *interfaceImpl) VariantIterInit(pSelf ConstVariantPtr, rIter UninitializedVariantPtr, rValid *uint8, ) Bool {
  return C.callVariantIterInit(me.ptrVariantIterInit, pSelf, rIter, rValid,)
}

func (me *interfaceImpl) VariantIterNext(pSelf ConstVariantPtr, rIter VariantPtr, rValid *uint8, ) Bool {
  return C.callVariantIterNext(me.ptrVariantIterNext, pSelf, rIter, rValid,)
}

func (me *interfaceImpl) VariantNewCopy(rDest UninitializedVariantPtr, pSrc ConstVariantPtr, )  {
  C.callVariantNewCopy(me.ptrVariantNewCopy, rDest, pSrc,)
}

func (me *interfaceImpl) VariantNewNil(rDest UninitializedVariantPtr, )  {
  C.callVariantNewNil(me.ptrVariantNewNil, rDest,)
}

func (me *interfaceImpl) VariantRecursiveHash(pSelf ConstVariantPtr, pRecursionCount Int, ) Int {
  return C.callVariantRecursiveHash(me.ptrVariantRecursiveHash, pSelf, pRecursionCount,)
}

func (me *interfaceImpl) VariantSet(pSelf VariantPtr, pKey ConstVariantPtr, pValue ConstVariantPtr, rValid *uint8, )  {
  C.callVariantSet(me.ptrVariantSet, pSelf, pKey, pValue, rValid,)
}

func (me *interfaceImpl) VariantSetIndexed(pSelf VariantPtr, pIndex Int, pValue ConstVariantPtr, rValid *uint8, rOob *uint8, )  {
  C.callVariantSetIndexed(me.ptrVariantSetIndexed, pSelf, pIndex, pValue, rValid, rOob,)
}

func (me *interfaceImpl) VariantSetKeyed(pSelf VariantPtr, pKey ConstVariantPtr, pValue ConstVariantPtr, rValid *uint8, )  {
  C.callVariantSetKeyed(me.ptrVariantSetKeyed, pSelf, pKey, pValue, rValid,)
}

func (me *interfaceImpl) VariantSetNamed(pSelf VariantPtr, pKey ConstStringNamePtr, pValue ConstVariantPtr, rValid *uint8, )  {
  C.callVariantSetNamed(me.ptrVariantSetNamed, pSelf, pKey, pValue, rValid,)
}

func (me *interfaceImpl) VariantStringify(pSelf ConstVariantPtr, rRet StringPtr, )  {
  C.callVariantStringify(me.ptrVariantStringify, pSelf, rRet,)
}

func (me *interfaceImpl) WorkerThreadPoolAddNativeGroupTask(pInstance ObjectPtr, pFunc unsafe.Pointer, pUserdata unsafe.Pointer, pElements int, pTasks int, pHighPriority Bool, pDescription ConstStringPtr, ) int64 {
  return C.callWorkerThreadPoolAddNativeGroupTask(me.ptrWorkerThreadPoolAddNativeGroupTask, pInstance, pFunc, pUserdata, pElements, pTasks, pHighPriority, pDescription,)
}

func (me *interfaceImpl) WorkerThreadPoolAddNativeTask(pInstance ObjectPtr, pFunc unsafe.Pointer, pUserdata unsafe.Pointer, pHighPriority Bool, pDescription ConstStringPtr, ) int64 {
  return C.callWorkerThreadPoolAddNativeTask(me.ptrWorkerThreadPoolAddNativeTask, pInstance, pFunc, pUserdata, pHighPriority, pDescription,)
}

func (me *interfaceImpl) XmlParserOpenBuffer(pInstance ObjectPtr, pBuffer *uint8, pSize uint64, ) Int {
  return C.callXmlParserOpenBuffer(me.ptrXmlParserOpenBuffer, pInstance, pBuffer, pSize,)
}

